// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ilsfkdfbonyzzutaywso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlsc2ZrZGZib255enp1dGF5d3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NTk1NDEsImV4cCI6MjA3MTIzNTU0MX0.6dbRhLUMzROvcOTCb0oGptaSHfe1biEmPEBMAmzFqBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);